### ISSUE TITLE
Did you fix that white flash happening at startup on every other dark theme?

### ISSUE THREAD

**Issue by adesurirey** [xypnox/xydark-typora#2]
On macOS, when opening Typora with any other dark theme, the whole window flashes white for half a second.

Xydark is one of the 2 themes that does not have it so I thought I would reach out to you, as I am struggling to identify the problem 😅

This is the issue I opened on Typora: https://github.com/typora/typora-issues/issues/3776

Do you know why Xydark don't flash at first open? 

Thanks.

**Comment by xypnox** [comment]
Hi @adesurirey,

I didn't notice the white flash until you pointed it out. On linux, I tried testing it myself and found out that with my theme, It sometimes does flash white and sometime it doesn't.

I think this issue is not at a theme level and might be with typora's internals.

Could you also try it multiple times to ensure that it doesn't show the white flash with several tries?

**Comment by adesurirey** [comment]
Hi @xypnox and thank you for answering!
I relaunched Typora several times again with Xydark on and it never blinked.

**Comment by adesurirey** [comment]
Fixed in Typora Version 0.9.9.36.2 (4901)
