### ISSUE TITLE
Brighter text in focus mode

### ISSUE THREAD

**Issue by KristjanHjartarson** [xypnox/xydark-typora#3]
Love the theme. I would like set the font of the focused text to a brigther setting, equal to the font in normal mode, while keeping the blur of the background text the same. Could you point me in the right direction?

**Comment by xypnox** [comment]
Hi @KristjanHjartarson, By text do you mean the currently open file in the sidebar?

Currently I change opacity of the sidebar to achieve the unfocused effect. To set a brighter text color, you would have to change the individual text colors of the sidebar to a darker shade and set the color of the selected file to your desire.

This needs to be done because the opacity value is set for the parent div of the sidebar and thus all the text inside has the same opacity so the text can't have color greater than #fff with 0.3 opacity in unfocused mode.

**Comment by KristjanHjartarson** [comment]
Thank you for a quick reply!

I mean the font itself. That is the font of the main text. I was wondering if you could turn the brightness (i.e., make the font more white) especially in focus mode. How would you go around doing that?

Thanks again. 
Kristjan

**Comment by xypnox** [comment]
Hi @KristjanHjartarson, The font colors are defined at: https://github.com/xypnox/xydark-typora/blob/34543a5ebbdb51e7e9f9edc981dd886c093d2e58/theme/xydark.css#L13, you can set it to a brighter hex value as per your preference.

Sorry for the late reply

**Comment by KristjanHjartarson** [comment]
This helped and I managed what i was trying to do. Thank you!

All the best

**Comment by xypnox** [comment]
Thanks for confirming :blush:. I will close this issue then.
